config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  # #read all
  # get "restaurants", to: "restaurants#index"
  # #new form
  # get "restaurants/new", to: "restaurants#new"
  # #send form to server and create
  # post "restaurants", to: "restaurants#create"
  # #read(one)
  # get "restaurants/:id",to: "restaurants#show", as: "restaurant"
  # #get edit form
  # get "restaurants/:id/edit", to: "restaurants#edit"
  # #patch request
  # patch "restaurants/:id", to: "restaurants#update"
  # #delete restaurant
  # delete "restaurants/:id", to: "restaurants#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show,:edit,:update,:destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end


  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
    #pick up information on the params
    #create a new restaurant with the information
    #save it
    #redirect to another page
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to @restaurant
    #pick up information on the params
    #update the restaurant
    #redirect to another page
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name,:address,:stars)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <div class="form-control">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div class="form-control">
  <%= f.label :address %>
  <%= f.text_field :address %>
  </div>
  <div class="form-control">
  <%= f.label :stars %>
  <%= f.text_field :stars %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<% @restaurants.each do |restaurant| %>
<h1><%= link_to restaurant.name, restaurant_path(restaurant) %></h1>
<p><%= restaurant.address %></p>
<p>
<% restaurant.stars.times do %>
 ⭐️
<% end %>
</p>

<% end %>

<%= link_to "New Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render "form" %>

app/views/restaurants/show.html.erb
<h1>Here is <%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p>
<% @restaurant.stars.times do %>
 ⭐️
<% end %>
</p>

<%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant) %>

<%= link_to "Delete", restaurant_path(@restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" } %>